### ISSUE TITLE
Compatibility to Vaadin 24

### ISSUE THREAD

**Issue by ben-geee** [xdev-software/vaadin-grid-exporter#80]
Hi there,
I recently updated my project to Vaadin 24. 

When opening GridExporter by just using

`GridExporter.newWithDefaults(grid).open(); `

then application throws following error at **_runtime_**.

```
'void com.vaadin.flow.component.button.Button.addThemeVariants(com.vaadin.flow.component.button.ButtonVariant[])'
java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.button.Button.addThemeVariants(com.vaadin.flow.component.button.ButtonVariant[])'
	at software.xdev.vaadin.grid_exporter.components.wizard.buttonbar.AbstractWizardButtonBar.lambda$initUI$1(AbstractWizardButtonBar.java:71)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at software.xdev.vaadin.grid_exporter.components.wizard.buttonbar.AbstractWizardButtonBar.initUI(AbstractWizardButtonBar.java:71)
```
 
I also tried it with a minimal Vaadin 23 and 24 project. Same behaviour. On V23 it works like charm and V24 same error. I really don't get it b/c method signature does not seem to have been changed or something like that.

Do you encounter same behaviour while on Vaadin 24?

Kind regards
Ben

**Comment by arivan-amin** [comment]
Same issue here with Vaadin 24. only went away by downgrading to Vaadin 23.

**Comment by PhineasClick** [comment]
Same here.

**Comment by AB-xdev** [comment]
Hi together,
Support for Vaadin 24 will be added with #93.

For more information have a look at the PR.
